#!/usr/bin/env python3
#
# XEvil(TM) Copyright (C) 1994,2000 Steve Hardt and Michael Judge
# http://www.xevil.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.  See gpl.txt.
#
"""gen_audio.py -- embed the XEvil sound assets into the binary.

Converts every sounds/*.wav and sounds/*.mp3 into a C source file holding one
byte array per file plus a manifest table {name, ptr, len}.  The generated file
is compiled as C (see sdl/makefile) and linked into the game; the shared sound
engine (x11/sound.cpp, built with -DXEVIL_EMBEDDED_AUDIO) then decodes every
soundtrack and effect straight from memory through a tiny in-RAM miniaudio VFS,
so no external "sounds" directory is needed -- the whole game is one file.

The manifest struct is declared in sdl/embedded_audio.h, which both this
generated file and sound.cpp include, keeping the layout in one place.

Encoding note: each byte becomes a 3-digit octal escape inside a C string
literal ("\\NNN").  Octal escapes are exactly three digits, so they are
unambiguous even when the following data byte is itself a digit, and the
compiler lexes a string literal ~20x faster than an equivalent {1,2,3,...}
integer-initializer array (measured on the 4.7 MB terraexm.mp3: 0.19s vs
3.56s).  A char/unsigned-char array initialised from a string literal is valid
C (this file MUST be compiled as C, not C++); the implicit trailing NUL makes
the array one byte longer than the asset, so the true length is recorded
separately in the manifest and used by the reader -- never sizeof.

Usage:  gen_audio.py <sounds_dir> <output.c>
"""

import os
import sys

# How many asset bytes to emit before closing the current string-literal
# fragment and starting a new one (adjacent string literals concatenate).  This
# keeps source lines bounded instead of emitting one multi-megabyte line, while
# staying coarse enough that the number of fragments -- and thus lexer work --
# is small.
BYTES_PER_FRAGMENT = 2048

# Only these extensions are embedded (the engine plays wav effects and mp3
# soundtracks; the parallel .mid files are unused by the miniaudio engine).
EXTENSIONS = (".wav", ".mp3")

# Precomputed octal escape for every possible byte value.
_OCT = ["\\%03o" % b for b in range(256)]


def c_symbol(filename):
    """A unique, valid C identifier derived from an asset filename."""
    return "xa_" + "".join(c if c.isalnum() else "_" for c in filename)


def emit_array(out, symbol, data):
    """Write `static const unsigned char <symbol>[] = "...";` for `data`."""
    out.write("static const unsigned char %s[] =\n" % symbol)
    n = len(data)
    if n == 0:
        out.write('  "";\n\n')
        return
    pos = 0
    while pos < n:
        chunk = data[pos:pos + BYTES_PER_FRAGMENT]
        out.write('  "')
        out.write("".join(_OCT[b] for b in chunk))
        out.write('"\n')
        pos += BYTES_PER_FRAGMENT
    out.write("  ;\n\n")


def main(argv):
    if len(argv) != 3:
        sys.stderr.write("usage: gen_audio.py <sounds_dir> <output.c>\n")
        return 2
    sounds_dir, out_path = argv[1], argv[2]

    names = sorted(f for f in os.listdir(sounds_dir)
                   if f.lower().endswith(EXTENSIONS))
    if not names:
        sys.stderr.write("gen_audio.py: no .wav/.mp3 assets in %s\n" % sounds_dir)
        return 1

    assets = []  # (filename, c_symbol, length)
    tmp_path = out_path + ".tmp"
    total = 0
    with open(tmp_path, "w") as out:
        out.write("/* GENERATED by sdl/gen_audio.py -- do not edit, do not commit. */\n")
        out.write('#include "embedded_audio.h"\n\n')
        for name in names:
            with open(os.path.join(sounds_dir, name), "rb") as fh:
                data = fh.read()
            sym = c_symbol(name)
            emit_array(out, sym, data)
            assets.append((name, sym, len(data)))
            total += len(data)

        out.write("const struct XevilEmbeddedAudio xevil_embedded_audio[] = {\n")
        for name, sym, length in assets:
            out.write('  { "%s", %s, %uu },\n' % (name, sym, length))
        out.write("};\n\n")
        out.write("const int xevil_embedded_audio_count = %d;\n" % len(assets))

    os.replace(tmp_path, out_path)
    sys.stderr.write("gen_audio.py: embedded %d assets (%d bytes) -> %s\n"
                     % (len(assets), total, out_path))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
