/* XPM */
// A stylized XEvil "X" -- the SDL window / taskbar icon.
static char *sdl_icon_xpm[] = {
  "32 32 3 1 0 0",
  " 	c None",
  ".	c #37C8B0",
  "o	c #0A3A34",
  "...oo                      oo...",
  "....oo                    oo....",
  ".....oo                  oo.....",
  "o.....oo                oo.....o",
  "oo.....oo              oo.....oo",
  " oo.....oo            oo.....oo ",
  "  oo.....oo          oo.....oo  ",
  "   oo.....oo        oo.....oo   ",
  "    oo.....oo      oo.....oo    ",
  "     oo.....oo    oo.....oo     ",
  "      oo.....oo  oo.....oo      ",
  "       oo.....oooo.....oo       ",
  "        oo.....oo.....oo        ",
  "         oo..........oo         ",
  "          oo........oo          ",
  "           oo......oo           ",
  "           oo......oo           ",
  "          oo........oo          ",
  "         oo..........oo         ",
  "        oo.....oo.....oo        ",
  "       oo.....oooo.....oo       ",
  "      oo.....oo  oo.....oo      ",
  "     oo.....oo    oo.....oo     ",
  "    oo.....oo      oo.....oo    ",
  "   oo.....oo        oo.....oo   ",
  "  oo.....oo          oo.....oo  ",
  " oo.....oo            oo.....oo ",
  "oo.....oo              oo.....oo",
  "o.....oo                oo.....o",
  ".....oo                  oo.....",
  "....oo                    oo....",
  "...oo                      oo..."
};
