/*
 * XEvil 2.5 SDL port -- in-memory XPM3 parser + baked named-color table.
 */

#include "xpm.h"

#include <cctype>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <unordered_map>

/* ------------------------------------------------------------------ *
 * Baked named-color table.
 *
 * This is the exact set of color NAMES actually referenced by the port's
 * compiled-in art and context data, generated by grepping:
 *   - every color entry across all 472 *.xpm files under x11/gen_xpm:
 *       ALL entries are '#RRGGBB' hex or 'None' -- ZERO named colors there.
 *   - every foreColorName / backColorName / colorName / foreground /
 *     background string in the cmn/bitmaps *.bitmaps files and the names in
 *     x11/xdata.cpp + x11/ui.cpp (human colors, window chrome, arena text).
 * The 35 names below are those string tokens cross-checked against the X11
 * rgb.txt database, plus the window-chrome names (grey40 alias, light grey).
 * RGB values are taken verbatim from /usr/share/X11/rgb.txt.
 *
 * Any name NOT in this table is a hard error (fail loudly) so a new color in
 * future art can never silently render as black/white.
 * ------------------------------------------------------------------ */
struct NamedColor {
  const char *name;   /* lowercase, no spaces */
  unsigned char r, g, b;
};

static const NamedColor kNamedColors[] = {
  {"antiquewhite3", 0xCD, 0xC0, 0xB0},
  {"azure",         0xF0, 0xFF, 0xFF},
  {"bisque4",       0x8B, 0x7D, 0x6B},
  {"black",         0x00, 0x00, 0x00},
  {"blue",          0x00, 0x00, 0xFF},
  {"blue2",         0x00, 0x00, 0xEE},
  {"brown",         0xA5, 0x2A, 0x2A},
  {"brown2",        0xEE, 0x3B, 0x3B},
  {"brown4",        0x8B, 0x23, 0x23},
  {"chocolate3",    0xCD, 0x66, 0x1D},
  {"chocolate4",    0x8B, 0x45, 0x13},
  {"cyan",          0x00, 0xFF, 0xFF},
  {"gray",          0xBE, 0xBE, 0xBE},
  {"grey",          0xBE, 0xBE, 0xBE},
  {"gray30",        0x4D, 0x4D, 0x4D},
  {"gray40",        0x66, 0x66, 0x66},
  {"grey40",        0x66, 0x66, 0x66},   /* Xvars_WINDOW_BORDER_COLOR */
  {"gray45",        0x73, 0x73, 0x73},
  {"gray60",        0x99, 0x99, 0x99},
  {"gray70",        0xB3, 0xB3, 0xB3},   /* Xvars_WINDOW_BG_COLOR */
  {"green1",        0x00, 0xFF, 0x00},
  {"green3",        0x00, 0xCD, 0x00},
  {"green4",        0x00, 0x8B, 0x00},
  {"lightgrey",     0xD3, 0xD3, 0xD3},   /* Xvars_BACKGROUND "light grey" */
  {"lightgray",     0xD3, 0xD3, 0xD3},
  {"olivedrab",     0x6B, 0x8E, 0x23},
  {"orange",        0xFF, 0xA5, 0x00},
  {"orangered",     0xFF, 0x45, 0x00},
  {"pink3",         0xCD, 0x91, 0x9E},
  {"purple",        0xA0, 0x20, 0xF0},
  {"red",           0xFF, 0x00, 0x00},
  {"red1",          0xFF, 0x00, 0x00},
  {"red2",          0xEE, 0x00, 0x00},
  {"red4",          0x8B, 0x00, 0x00},
  {"steelblue",     0x46, 0x82, 0xB4},
  {"tan",           0xD2, 0xB4, 0x8C},
  {"white",         0xFF, 0xFF, 0xFF},
  {"yellow",        0xFF, 0xFF, 0x00},
};

static std::string normalize_name(const char *name) {
  std::string out;
  for (const char *p = name; *p; ++p) {
    if (*p == ' ' || *p == '\t')
      continue;
    out.push_back((char)std::tolower((unsigned char)*p));
  }
  return out;
}

namespace xpm {

bool lookup_named_color(const char *name,
                        unsigned char &r, unsigned char &g, unsigned char &b) {
  std::string key = normalize_name(name);
  const int n = (int)(sizeof(kNamedColors) / sizeof(kNamedColors[0]));
  for (int i = 0; i < n; i++) {
    if (key == kNamedColors[i].name) {
      r = kNamedColors[i].r;
      g = kNamedColors[i].g;
      b = kNamedColors[i].b;
      return true;
    }
  }
  return false;
}

}  // namespace xpm

/* --- helpers --- */

struct Rgba {
  unsigned char r, g, b, a;
};

static int hexval(char c) {
  if (c >= '0' && c <= '9') return c - '0';
  if (c >= 'a' && c <= 'f') return c - 'a' + 10;
  if (c >= 'A' && c <= 'F') return c - 'A' + 10;
  return -1;
}

/* Parse "#RGB" / "#RRGGBB" / "#RRRRGGGGBBBB".  Returns false on bad input. */
static bool parse_hex_color(const char *s, Rgba &out) {
  if (*s != '#')
    return false;
  const char *h = s + 1;
  int len = (int)std::strlen(h);
  for (int i = 0; i < len; i++)
    if (hexval(h[i]) < 0)
      return false;
  int r, g, b;
  if (len == 3) {
    r = hexval(h[0]) * 17;
    g = hexval(h[1]) * 17;
    b = hexval(h[2]) * 17;
  } else if (len == 6) {
    r = hexval(h[0]) * 16 + hexval(h[1]);
    g = hexval(h[2]) * 16 + hexval(h[3]);
    b = hexval(h[4]) * 16 + hexval(h[5]);
  } else if (len == 12) {              /* 4 hex per channel: take high byte */
    r = hexval(h[0]) * 16 + hexval(h[1]);
    g = hexval(h[4]) * 16 + hexval(h[5]);
    b = hexval(h[8]) * 16 + hexval(h[9]);
  } else {
    return false;
  }
  out.r = (unsigned char)r;
  out.g = (unsigned char)g;
  out.b = (unsigned char)b;
  out.a = 255;
  return true;
}

/* From a color spec line (already past the cpp-char key), pick the 'c' color
   value (fall back to g/g4/m if there is no 'c').  Returns "" if none found. */
static std::string extract_color_value(const std::string &rest) {
  /* tokenize on whitespace */
  std::string tokens[32];
  int nt = 0;
  size_t i = 0, N = rest.size();
  while (i < N && nt < 32) {
    while (i < N && std::isspace((unsigned char)rest[i])) i++;
    if (i >= N) break;
    size_t start = i;
    while (i < N && !std::isspace((unsigned char)rest[i])) i++;
    tokens[nt++] = rest.substr(start, i - start);
  }
  const char *want[] = {"c", "g", "g4", "m"};  /* preference order */
  for (int w = 0; w < 4; w++) {
    for (int t = 0; t + 1 < nt; t++) {
      if (tokens[t] == want[w]) {
        /* A color name could span multiple tokens (e.g. "light grey"); join
           until the next key token. */
        std::string val = tokens[t + 1];
        static const char *keys[] = {"c", "g", "g4", "m", "s"};
        for (int t2 = t + 2; t2 < nt; t2++) {
          bool isKey = false;
          for (int k = 0; k < 5; k++)
            if (tokens[t2] == keys[k]) { isKey = true; break; }
          if (isKey) break;
          val += " ";
          val += tokens[t2];
        }
        return val;
      }
    }
  }
  return "";
}

namespace xpm {

bool parse(const char *const *data, XpmImage &out) {
  out.reset();
  if (!data || !data[0]) {
    std::fprintf(stderr, "xpm::parse: null data\n");
    return false;
  }

  int w = 0, h = 0, ncolors = 0, cpp = 0, hotx = 0, hoty = 0;
  int got = std::sscanf(data[0], "%d %d %d %d %d %d",
                        &w, &h, &ncolors, &cpp, &hotx, &hoty);
  if (got < 4 || w <= 0 || h <= 0 || ncolors <= 0 || cpp <= 0) {
    std::fprintf(stderr, "xpm::parse: bad header \"%s\"\n", data[0]);
    return false;
  }
  if (got < 6) { hotx = 0; hoty = 0; }

  std::unordered_map<std::string, Rgba> cmap;
  cmap.reserve(ncolors * 2);

  for (int i = 0; i < ncolors; i++) {
    const char *line = data[1 + i];
    if (!line || (int)std::strlen(line) < cpp) {
      std::fprintf(stderr, "xpm::parse: truncated color entry %d\n", i);
      return false;
    }
    std::string key(line, cpp);
    std::string rest(line + cpp);
    std::string val = extract_color_value(rest);
    if (val.empty()) {
      std::fprintf(stderr, "xpm::parse: no color value in entry \"%s\"\n", line);
      return false;
    }
    Rgba c;
    if (strcasecmp(val.c_str(), "none") == 0) {
      c.r = c.g = c.b = 0;
      c.a = 0;                       /* transparent -> alpha 0 (== the mask) */
    } else if (val[0] == '#') {
      if (!parse_hex_color(val.c_str(), c)) {
        std::fprintf(stderr, "xpm::parse: bad hex color \"%s\"\n", val.c_str());
        return false;
      }
    } else {
      if (!lookup_named_color(val.c_str(), c.r, c.g, c.b)) {
        std::fprintf(stderr,
                     "xpm::parse: UNKNOWN named color \"%s\" -- add it to the "
                     "baked table in sdl/xpm.cpp\n", val.c_str());
        return false;
      }
      c.a = 255;
    }
    cmap[key] = c;
  }

  size_t npix = (size_t)w * h;
  unsigned char *rgba = (unsigned char *)std::malloc(npix * 4);
  if (!rgba) {
    std::fprintf(stderr, "xpm::parse: out of memory\n");
    return false;
  }

  int unknownPix = 0;
  for (int y = 0; y < h; y++) {
    const char *row = data[1 + ncolors + y];
    int rowlen = row ? (int)std::strlen(row) : 0;
    for (int x = 0; x < w; x++) {
      Rgba c;
      c.r = c.g = c.b = 0;
      c.a = 0;
      int off = x * cpp;
      if (off + cpp <= rowlen) {
        std::string key(row + off, cpp);
        std::unordered_map<std::string, Rgba>::iterator it = cmap.find(key);
        if (it != cmap.end())
          c = it->second;
        else
          unknownPix++;
      } else {
        unknownPix++;
      }
      unsigned char *px = rgba + ((size_t)y * w + x) * 4;
      px[0] = c.r;
      px[1] = c.g;
      px[2] = c.b;
      px[3] = c.a;
    }
  }
  if (unknownPix)
    std::fprintf(stderr,
                 "xpm::parse: warning: %d pixel(s) referenced an undefined key "
                 "(rendered transparent)\n", unknownPix);

  out.width = w;
  out.height = h;
  out.hotx = hotx;
  out.hoty = hoty;
  out.rgba = rgba;
  return true;
}

}  // namespace xpm

/* --- XpmImage members --- */

void XpmImage::reset() {
  if (rgba) {
    std::free(rgba);
    rgba = 0;
  }
  width = height = 0;
  hotx = hoty = 0;
}

XpmImage::~XpmImage() {
  if (rgba)
    std::free(rgba);
}
